spring:
  application:
    name: api-gateway

server:
  port: 3000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka/
zuul:
  routes:
    eureka-consumer-ribbon-hystrix: /service/**
