spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zackor/springCloudDemo
          username: zackor@163.com
          password: 123qweASD
          search-paths: config-repo

server:
  port: 1201